apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: platform/prod/db-credentials
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: platform/prod/db-credentials
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: platform/prod/db-credentials
        property: dbname
    - secretKey: DB_USER
      remoteRef:
        key: platform/prod/db-credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: platform/prod/db-credentials
        property: password
