apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.0
    helm:
      valueFiles:
        - $values/gitops/prod/helm-values/alb-controller.yaml
  sources:
    - repoURL: https://github.com/yamenmehdizade/platform-infra
      targetRevision: master
      ref: values
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.13.0
      helm:
        valueFiles:
          - $values/gitops/prod/helm-values/alb-controller.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
