apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.0
    helm:
      valueFiles:
        - $values/gitops/prod/helm-values/cert-manager.yaml
  sources:
    - repoURL: https://github.com/yamenmehdizade/platform-infra
      targetRevision: master
      ref: values
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.17.0
      helm:
        valueFiles:
          - $values/gitops/prod/helm-values/cert-manager.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
